Vastly improve player movement + major player code refactor
Valks-Games/sankari pull request #167
Opened 2022-10-09 00:39 UTC by valkyrienyanko

- Fixes a ton of issues presented in #136
- A lot of the code related to EntityCommand has been deleted and replaced with a new class called PlayerCommand in Player.cs (all other EntityCommand classes have been left untouched)

## Known Issues
- Wall jumping and dashing is currently not implemented / has been temporarily disabled
- Player does not slide down slope but rather bounces down slope
- Player jump power based on how long you hold jump key has not been implemented

2022-10-09 00:47 UTC, policiu commented
I believe that Dash and Wall Jump should be re-introduced to Player, even if it isn't working. At the very least, leave the framework in, even if we don't call them.

2022-10-09 01:26 UTC, policiu requested changes
Nice clean up. Separating the animations and movement is a little messy since they relate so closely together. I'm a little hesitant on how little PlayerCommandAudio relates to PlayerCommand. I'm not sure if there is a clean solution.

2022-10-09 01:26 UTC, policiu commented on Scripts/Entities/Player/PlayerCommandAudio.cs
> +		Audio.PlaySFX("player_jump", 80);
I'm wondering if we want to use signals/events instead of methods... Not sure.

If events (Excuse formatting, I did it in github)

```csharp

class Player() {

Event OnJump

HandleInput()
{
  if (input.jump)
  {
    OnJump.?Invoke(); 
  }
}
}

Command
{
     Player.OnJump += HandleJump;
}
```

2022-10-09 01:26 UTC, policiu commented on Scripts/Entities/Player/PlayerCommandAnimation.cs
> +	private async void OnDieTweenCompleted()
This should be in player as this isn't an animation.

2022-10-09 01:26 UTC, policiu commented on Scripts/Entities/Player/Player.cs
> +			PlayerCommands.ForEach(cmd => cmd.FinishedLevel());
I think HaltPlayerLogic makes sense to do here still.

2022-10-09 01:26 UTC, policiu commented on Scripts/Entities/Player/Player.cs
> +			var JumpForce = 500;
Old code? (Is JumpForce supposed to be here instead of the property JumpForce?

2022-10-09 01:26 UTC, policiu commented on Scripts/Entities/Player/Player.cs
> +	public Vector2 PlayerVelocity; // this was made as a field intentionally
I removed it since it confusing that we have a PlayerVelocity and a Velocity. Additionally if a command changes Velocity, it'll be overridden by PlayerVelocity. Interfaces cannot reference fields.

You will need to either use Velocity or figure out a clean way for each command to reference PlayerVelocity.

2022-10-09 03:44 UTC, valkyrienyanko commented
> I believe that Dash and Wall Jump should be re-introduced to Player, even if it isn't working. At the very least, leave the framework in, even if we don't call them.

I never tested them but I'm very confident I can get them working. Just wondering how to integrate them into the code.

2022-10-09 03:46 UTC, valkyrienyanko commented on Scripts/Entities/Player/PlayerCommandAnimation.cs
> +	public override void Update(float delta)
Yes and I convert them to floats as I have no needs for double precision.

2022-10-09 03:47 UTC, valkyrienyanko commented on Scripts/Entities/Player/PlayerCommand.cs
> +public abstract class PlayerCommand
I have yet to see the benefit from this.

2022-10-09 03:48 UTC, valkyrienyanko commented on Scripts/Entities/Player/PlayerCommandAnimation.cs
> +		Player.AnimatedSprite.Play("jump_start");
Yeah I noticed that too, I didn't see this part of the code though or I saw it but it just went over my head. I'll have to look into this.

2022-10-09 03:48 UTC, valkyrienyanko commented on Scripts/Entities/Player/PlayerCommandMovement.cs
> +		var x = -Convert.ToInt32(input.IsLeft) + Convert.ToInt32(input.IsRight);
Noted, will look into.

2022-10-09 03:50 UTC, valkyrienyanko commented on Scripts/Entities/Player/PlayerCommandMovement.cs
> +		Player.PlayerVelocity.y -= Player.JumpForce;
The `Vector2.Up.y` looks the nicest out of the 2 you've shown.

I would just leave it as is.

2022-10-09 04:01 UTC, valkyrienyanko commented on Scripts/Entities/Player/PlayerCommandAudio.cs
> +		Audio.PlaySFX("player_jump", 80);
What is the difference between this and the Notifications.cs class?

What is the benefit of using events like this in this particular scenario?

2022-10-09 04:03 UTC, valkyrienyanko commented on Scripts/Entities/Player/Player.cs
> +			var JumpForce = 500;
I didn't put much thought when doing this. The property should be used here.

2022-10-09 04:04 UTC, valkyrienyanko commented on Scripts/Entities/Player/Player.cs
> +	public Vector2 PlayerVelocity; // this was made as a field intentionally
I can't use Velocity because it's a property struct which isn't modifiable directly

I'm not sure how else I would do this

2022-10-09 04:05 UTC, valkyrienyanko commented on Scripts/Entities/Player/Player.cs
> +			PlayerCommands.ForEach(cmd => cmd.FinishedLevel());
I was just trying to keep everything together so it's easier to see the big picture when coming back to it

2022-10-09 04:05 UTC, valkyrienyanko commented on Scripts/Entities/Player/PlayerCommandAnimation.cs
> +	private async void OnDieTweenCompleted()
I disagree, the method could be renamed to `OnDieAnimationCompleted` which would better suit where it is right now.

2022-10-09 15:25 UTC, policiu commented on Scripts/Entities/Player/PlayerCommand.cs
> +public abstract class PlayerCommand
From what the PlayerSkills class? Inheriting from EntityCommand?

2022-10-09 15:27 UTC, policiu commented on Scripts/Entities/Player/PlayerCommandMovement.cs
> +		Player.PlayerVelocity.y -= Player.JumpForce;
No complaints

2022-10-09 15:35 UTC, policiu commented on Scripts/Entities/Player/PlayerCommandAudio.cs
> +		Audio.PlaySFX("player_jump", 80);
Notifications essentially just reimplements C# Events. Additionally, we can't have arguments with the notification system unlike events.

As an aside, we probably should just use Godot's signal interface since they show up in the Inspector: https://docs.godotengine.org/en/latest/getting_started/step_by_step/signals.html

2022-10-09 15:36 UTC, policiu commented on Scripts/Entities/Player/PlayerCommandAnimation.cs
> +	private async void OnDieTweenCompleted()
Why do you disagree? 

As an aside, this would be a great place for an event.

2022-10-09 15:38 UTC, policiu commented on Scripts/Entities/Player/Player.cs
> +			PlayerCommands.ForEach(cmd => cmd.FinishedLevel());
Can you go into more detail? Isn't easier to see the big picture if we have HaltPlayerLogic wrap around Complete Level? Conceptually, we are HaltingPlayerLogic while completing the level.

2022-10-09 15:39 UTC, policiu commented on Scripts/Entities/Player/Player.cs
> +	public Vector2 PlayerVelocity; // this was made as a field intentionally
Look how the entity commands do it. It uses local variables.

2022-10-09 15:39 UTC, policiu commented on Scripts/Entities/Player/PlayerCommandAnimation.cs
> +	public override void Update(float delta)
No complaints.

2022-10-09 16:55 UTC, valkyrienyanko commented on Scripts/Entities/Player/PlayerCommandAudio.cs
> +		Audio.PlaySFX("player_jump", 80);
Notifications.cs does support arguments.

I had a look at Godot signals. Just figured out how to use them. I'll try making use of them.

2022-10-09 17:05 UTC, valkyrienyanko commented on Scripts/Entities/Player/PlayerCommandAnimation.cs
> +		Player.AnimatedSprite.Play("jump_start");
![image](https://user-images.githubusercontent.com/6277739/194769973-dcecd734-376d-4d96-a187-7a3cd004da11.png)

The problem is the idle animation is constantly taking priority.

2022-10-09 17:18 UTC, valkyrienyanko commented on Scripts/Entities/Player/PlayerCommand.cs
> +public abstract class PlayerCommand
`EntityCommand` has `void Update(MovementInput input)`, `PlayerCommand` has `void Update(float delta)`. Their different so I'm going to have to change a few things if I want `PlayerCommand` to inherit from `EntityCommand`. Why does `EntityCommand` have `MovementInput input` as a param? There is only player related stuff in `MovementInput`.

2022-10-09 17:20 UTC, valkyrienyanko commented
![image](https://user-images.githubusercontent.com/6277739/194770562-984961e2-3e27-4467-9aa6-f0dff0649d50.png)

Just realized this code should not be in Start(), it should be in Update()

2022-10-09 17:24 UTC, valkyrienyanko commented on Scripts/Entities/Player/PlayerCommand.cs
> +public abstract class PlayerCommand
a0ec18edb7f20961b5bff723daf85585f862daca resolves this

2022-10-09 17:26 UTC, valkyrienyanko commented on Scripts/Entities/Player/PlayerCommandMovement.cs
> +		var x = -Convert.ToInt32(input.IsLeft) + Convert.ToInt32(input.IsRight);
7c8d82f9378bb35834f79eb72b48040f42d46df6 resolves this

2022-10-09 17:42 UTC, valkyrienyanko commented on Scripts/Entities/Player/PlayerCommandAudio.cs
> +		Audio.PlaySFX("player_jump", 80);
I just tried using a Godot event but realized that not only the emitter but the listener too both need to extend from `Godot.Object`. So for example a `CommandXXX` class needs to extend from `Godot.Object` to listen to an event. This is undesired. This makes me want to stick with Notifications.cs or look into another solution.

2022-10-09 17:44 UTC, valkyrienyanko commented on Scripts/Entities/Player/PlayerCommandAnimation.cs
> +	private async void OnDieTweenCompleted()
![image](https://user-images.githubusercontent.com/6277739/194771542-f89387fe-2ea7-4e9c-822c-57835cff7769.png)

Everything here is related to an animation / making a cutscene.

2022-10-09 17:48 UTC, valkyrienyanko commented on Scripts/Entities/Player/Player.cs
> +			PlayerCommands.ForEach(cmd => cmd.FinishedLevel());
Since this function is not returning a task, I'm just going to leave it the way it is right now. The reason I did not make it a task is because in the future I might remove await from inside this function and remove the async stuff. I'm not sure yet.

![image](https://user-images.githubusercontent.com/6277739/194771667-4d2e1c1e-69f7-406e-94de-9c8a1864742e.png)

2022-10-09 17:49 UTC, valkyrienyanko commented on Scripts/Entities/Player/Player.cs
> +			var JumpForce = 500;
758117d98e8da70fed3c019aa218789e1465bd3d resolves this

2022-10-09 17:51 UTC, valkyrienyanko commented on Scripts/Entities/Player/Player.cs
> +	public Vector2 PlayerVelocity; // this was made as a field intentionally
![image](https://user-images.githubusercontent.com/6277739/194771845-71810b9f-5715-4d86-a421-7873fccfd4a1.png)

Assuming this code is in Update(), this would break the velocity logic. I've tried this before, it breaks. I don't know exactly why but it probably has something to do with setting the player velocity variable twice.

2022-10-09 18:15 UTC, valkyrienyanko commented on Scripts/Entities/Player/PlayerCommandAudio.cs
> +		Audio.PlaySFX("player_jump", 80);
Just realized that Notifications.cs also relies on classes extending from Godot.Node but that can be fixed I think.

2022-10-09 19:27 UTC, valkyrienyanko commented on Scripts/Entities/Player/PlayerCommandAudio.cs
> +		Audio.PlaySFX("player_jump", 80);
Notifications.cs (now called EventManager.cs) no longer relies on Godot.Node.

Differences between EventManager.cs and Godot Signals

**Godot Signals**
- Requires emitter and listener to extend from node

**EventManager.cs**
- Does not require class to extend from anything and class can be static if desired (for e.g. see Net.cs)
- Syntax is simpler

2022-10-09 19:30 UTC, valkyrienyanko commented on Scripts/Entities/Player/PlayerCommandAudio.cs
> +		Audio.PlaySFX("player_jump", 80);
**Audio.cs**
![image](https://user-images.githubusercontent.com/6277739/194775974-3a6429c8-7d4c-4f60-b946-787708f38b1d.png)

And it works just fine :)

2022-10-09 19:34 UTC, valkyrienyanko commented on Scripts/Entities/Player/PlayerCommandAudio.cs
> +		Audio.PlaySFX("player_jump", 80);
![image](https://user-images.githubusercontent.com/6277739/194776092-596ed4bc-ba56-4159-9ca0-9182a72d64ac.png)

2022-10-09 19:37 UTC, valkyrienyanko commented on Scripts/Entities/Player/PlayerCommandAudio.cs
> +		Audio.PlaySFX("player_jump", 80);
I don't think I can transition player animations over to events. I think this is only possible with a state machine?

2022-10-09 20:15 UTC, policiu requested changes
Nice job, we are getting pretty close to cleaning up the refactor. I do want the commands reintroduced so that we aren't breaking functionality.

> I believe that Dash and Wall Jump should be re-introduced to Player, even if it isn't working. At the very least, leave the framework in, even if we don't call them.
> 
> I never tested them but I'm very confident I can get them working. Just wondering how to integrate them into the code.

Well you removed the `PlayerSkills` object which handled them. (The goal of `PlayerSkills `was so that we didn't have to do `PlayerCommands[0].Stop() `and instead use `PlayerCommands.DashCommand.Stop() `which is much safer.)

If you decide to do C# events and need help let me know!

2022-10-09 20:15 UTC, policiu commented on Scripts/Entities/Player/Player.cs
> +			var JumpForce = 500;
Looks good

2022-10-09 20:18 UTC, valkyrienyanko commented on Scripts/Entities/Player/PlayerCommandAnimation.cs
> +	private async void OnDieTweenCompleted()
It's all intertwined right now, would be difficult to unwind it.

2022-10-09 20:20 UTC, valkyrienyanko commented on Scenes/Main.tscn
> +LoadTestLevel = true
Would be nice if there was a .gitignore function to ignore specific code changes from files. But I'll try to remember to stop committing these changes.

2022-10-09 20:22 UTC, valkyrienyanko commented
> Well you removed the PlayerSkills object which handled them. (The goal of PlayerSkills was so that we didn't have to do PlayerCommands[0].Stop() and instead use PlayerCommands.DashCommand.Stop() which is much safer.)

Alternative to what you're doing

![image](https://user-images.githubusercontent.com/6277739/194777844-1e70d5ce-b8bc-4939-bf4a-8a169fa00fb3.png)

2022-10-09 20:30 UTC, policiu commented on Scripts/Entities/Player/PlayerCommandAudio.cs
> +		Audio.PlaySFX("player_jump", 80);
@valkyrienyanko Potentially replacing Notifications/Event Manager with C# events should not be done in this PR. Let's try to keep this PR contained to the Player.

2022-10-09 20:32 UTC, valkyrienyanko commented on Scripts/Entities/Player/PlayerCommandAudio.cs
> +		Audio.PlaySFX("player_jump", 80);
Alright

2022-10-09 21:26 UTC, valkyrienyanko commented
Nvm my bad the wall jump code should not be in Update(), it should be in Start()

2022-10-09 21:45 UTC, valkyrienyanko commented
New issues presented themselves with these new changes
- [ ] Player cannot jump when in a corner
- [ ] Player can climb a wall forever (for example, say there is a wall on the left, the player could just hold down `D` while pressing jump to climb infinitely. To prevent this the player input should be disabled during a wall jump for a set duration

2022-10-09 21:48 UTC, valkyrienyanko commented
Dev note: `PlayerEvent.OnJump` exists in several places in code but is not being used

2022-10-09 21:54 UTC, valkyrienyanko commented
Wall jumping feels weird, the player just goes up in a upward diagonal line then stops.

2022-10-09 21:54 UTC, valkyrienyanko commented
Fast falling whilst on a slope (hold down key) is too sudden (try increasing the fast fall speed in `PlayerCommandWallJump` to see the teleport effect more. Some kind of acceleration needs to be applied here.

2022-10-09 21:56 UTC, valkyrienyanko commented
The animation state machine should take priority over everything above. (specifically displaying the correct flipped sprite when on a wall and when idle, and getting the jump_start animation to take priority over everything else) (in other words the issue is the animation jump_fall is being set every frame overriding the animation jump_start which is not set every frame)

2022-10-09 22:43 UTC, policiu commented
test

2022-10-09 22:47 UTC, policiu requested changes
I highly disagree:
1. Making Dash a player command. Dash is generic enough to be usable by other entities (Wall jump is probably fine, but I still disagree with that as well. Enemies who scale walls could be neat)
2. Removing the interface to Dash see 1
3. Using Player instead of Entity. Using EntityCommand<Player> sets Entity to a player object.


Also, when renaming files, please use `git mv` so that history is preserved.

2022-10-09 22:47 UTC, policiu commented on Scripts/Entities/Level/Coin.cs
> +			GameManager.Events.Notify(Event.OnCoinPickup);
Formatting

2022-10-09 22:47 UTC, policiu commented on Scripts/Entities/Player/PlayerCommand.cs
> +public abstract class PlayerCommand : EntityCommand
I would make this
```suggestion
public abstract class PlayerCommand : EntityCommand<Player>
```

and remove the Player property.

2022-10-09 22:47 UTC, policiu commented on Scripts/Entities/Player/PlayerCommandAnimation.cs
> +	private async void OnDieTweenCompleted()
Fine to close.

2022-10-09 22:47 UTC, policiu commented on Scripts/Entities/Player/PlayerCommand.cs
> +	public override void Update(float delta) { }
No need to override if we aren't changing the method.

2022-10-09 22:47 UTC, policiu commented on Scripts/Entities/Player/PlayerCommandAnimation.cs
> +		Player.AnimatedSprite.Play("jump_start");
Continued in a different thread.

2022-10-09 22:54 UTC, valkyrienyanko commented
> 1. Making Dash a player command. Dash is generic enough to be usable by other entities (Wall jump is probably fine, but I still disagree with that as well. Enemies who scale walls could be neat)

Maybe for enemies but not the player as I want to make levels more interesting. Otherwise the player will just be able to go straight up no matter where they are 👀

2022-10-09 22:55 UTC, valkyrienyanko commented
> 2. Removing the interface to Dash see 1

You can add it back

2022-10-09 22:55 UTC, valkyrienyanko commented
> Using Player instead of Entity. Using EntityCommand sets Entity to a player object.

PlayerCommand extends from EntityCommand but feel free to change it back.

2022-10-09 22:56 UTC, valkyrienyanko commented
> Also, when renaming files, please use git mv so that history is preserved.

How does this work with GitHub desktop app?

2022-10-09 22:59 UTC, valkyrienyanko commented on Scripts/Entities/Level/Coin.cs
> +			GameManager.Events.Notify(Event.OnCoinPickup);
Looks fine to me

![image](https://user-images.githubusercontent.com/6277739/194783486-79f4fd86-e79b-4439-aa24-1c9735c43473.png)

2022-10-09 23:01 UTC, valkyrienyanko commented on Scripts/Entities/Player/PlayerCommand.cs
> +public abstract class PlayerCommand : EntityCommand
I'll leave that up to you unless if you want me to convert the player commands back to entity commands and do this suggestion I can do it but I would prefer you do it.

2022-10-09 23:03 UTC, valkyrienyanko commented on Scripts/Entities/Player/PlayerCommand.cs
> +	public override void Update(float delta) { }
So you just mean `public void Update(float delta) {}`. You mean just remove the `override` keyword?

2022-10-09 23:19 UTC, policiu commented on Scripts/Entities/Level/Coin.cs
> +			GameManager.Events.Notify(Event.OnCoinPickup);
Tabs vs spaces.

2022-10-09 23:20 UTC, policiu commented on Scripts/Entities/Player/PlayerCommand.cs
> +public abstract class PlayerCommand : EntityCommand
As long as you revert the Dash (and maybe Wall Jump) back to EntityCommands, I could handle the new commands.

2022-10-09 23:20 UTC, policiu commented on Scripts/Entities/Player/PlayerCommand.cs
> +	public override void Update(float delta) { }
Outright delete the function.

2022-10-09 23:20 UTC, policiu commented
> > 1. Making Dash a player command. Dash is generic enough to be usable by other entities (Wall jump is probably fine, but I still disagree with that as well. Enemies who scale walls could be neat)
> 
> Maybe for enemies but not the player as I want to make levels more interesting. Otherwise the player will just be able to go straight up no matter where they are 👀

I think you misunderstand, I'm just saying that the wall jump command should be a EntityCommand.


> > 2. Removing the interface to Dash see 1
> 
> You can add it back

I could, but that's a waste of time since I would be reverting this PR's changes. We need to come to an agreement on the new changes or revert the changes.

> > Also, when renaming files, please use git mv so that history is preserved.
> 
> How does this work with GitHub desktop app? (as that's what I'm using for all git-version control management)

My bad I didn't realize that you made a new file instead of renaming and moving the old one.

2022-10-09 23:47 UTC, valkyrienyanko commented on Scripts/Entities/Level/Coin.cs
> +			GameManager.Events.Notify(Event.OnCoinPickup);
I think I have it set to tabs

2022-10-09 23:51 UTC, valkyrienyanko commented on Scripts/Entities/Player/PlayerCommand.cs
> +	public override void Update(float delta) { }
Done see 704b8ffa7765114b486bd50ce5f8fd98fc7e96d5

2022-10-09 23:53 UTC, valkyrienyanko commented
> I think you misunderstand, I'm just saying that the wall jump command should be a EntityCommand.

I agree but there should be a version of the wall jumps where a entity has to have 2 walls to ascend infinite heights as suppose to only having 1 wall to ascend infinite heights.

2022-10-10 00:13 UTC, valkyrienyanko commented on Scripts/Entities/Player/PlayerCommandAnimation.cs
> +		Player.AnimatedSprite.Play("jump_start");
Can you send a link to this thread?

2022-10-10 00:14 UTC, valkyrienyanko commented on Scripts/Entities/Player/PlayerCommandAudio.cs
> +		Audio.PlaySFX("player_jump", 80);
Going to be using EventManager.cs for all events.

2022-10-10 00:17 UTC, valkyrienyanko commented on Scripts/Entities/Player/Player.cs
> +	public Vector2 PlayerVelocity; // this was made as a field intentionally
![image](https://user-images.githubusercontent.com/6277739/194786007-ac89effc-58f5-465c-8903-f8efb03fbb37.png)

This will break dash code. I'm not sure what you mean by switching to local variables sorry.

2022-10-10 00:19 UTC, valkyrienyanko commented on Scripts/Entities/Player/PlayerCommand.cs
> +public abstract class PlayerCommand : EntityCommand
The old dash command code had bugs, the way it is now, those bugs are gone so I'm not sure how I would revert it?

2022-10-10 01:17 UTC, policiu requested changes
Getting there, but not quite.

> I could, but that's a waste of time since I would be reverting this PR's changes. We need to come to an agreement on the new changes or revert the changes.

You did not address this fully. We should meet and talk (read as type ha) about this to avoid more back and forth. I'm available after 7pm EST tomorrow.

2022-10-10 01:17 UTC, policiu commented on Scripts/Entities/Player/Player.cs
> +	public Vector2 PlayerVelocity; // this was made as a field intentionally
You need to remove `PlayerVelocity` and do `Velocity` _everywhere_ (in dash, wall jump, gravity, horizontal, etc.)

2022-10-10 01:17 UTC, policiu commented on Scripts/Entities/Player/PlayerCommandDash.cs
> +		Entity.CurrentlyDashing = false;
CurrentlyDashing isn't that closely related to the Player. Instead it's related to the Dash command. Consider reverting this change back to when CurrentlyDashing was a public property of DashCommand. Then, in Player, we can get it by `PlayerCommands[enum.Dash].CurrentlyDashing`

2022-10-10 01:17 UTC, policiu commented on Scripts/Entities/Player/PlayerCommandWallJump.cs
> +				var JumpForceWallVert = 600;
Consider making these properties.

2022-10-11 02:19 UTC, policiu requested changes
Getting closer!

2022-10-11 02:19 UTC, policiu commented on Scripts/Entities/Commands/EntityCommandDash.cs
> +	public GTimer  DontCheckPlatformAfterDashDuration { get; set; }
temp

2022-10-11 02:19 UTC, policiu commented on Scripts/Entities/Commands/EntityCommandMovement.cs
> +		Entity.Velocity = velocity;
Optional:
```suggestion
		Velocity = new Vector2(ClampAndDampen(velocity.x, DampeningGround, MaxSpeedSprint),Velocity.y);
```

For these and other similar functions as well. Update air is probably fine.

2022-10-11 02:19 UTC, policiu commented on Scripts/Entities/Player/Player.cs
> +public partial class Player : CharacterBody2D, IEntityMoveable, IEntityDash, IEntityWallJumpable
Player needs `IEntityMovement`

2022-10-11 02:19 UTC, policiu commented on Scripts/Entities/Player/Player.cs
> +	private Dictionary<PlayerCommandType, PlayerCommand> PlayerCommands { get; set; }
Need this to be `Dictionary<PlayerCommandType, EntityCommand>` or have a separate one. This will break all references to functions defined in `PlayerCommand,` so you'll need to account for that. You have quite a few options.

2022-10-11 02:19 UTC, policiu commented on Scripts/Entities/Commands/EntityCommandWallJump.cs
> +				if (Entity.PlayerInput.IsDown)
As a temp workaround:

`if (Entity is Player player)`

2022-10-11 22:05 UTC, valkyrienyanko commented on Scripts/Entities/Commands/EntityCommandMovement.cs
> +		Entity.Velocity = velocity;
![image](https://user-images.githubusercontent.com/6277739/195206934-0edaf9cb-83b0-45b1-9ca8-cae519c742fa.png)

I prefer `B`

2022-10-11 22:30 UTC, valkyrienyanko commented
Because of my lack of knowledge of git and the hassle of getting everything to work, I'm just going to commit all new changes here until this PR is closed.

2022-10-12 00:35 UTC, policiu commented
> Because of my lack of knowledge of git and the hassle of getting everything to work, I'm just going to commit all new changes here until this PR is closed.

Please revert the changes that aren't related to what we were talking about. I don't want to review them here. This PR is too complex. If you need help lmk

2022-10-12 00:35 UTC, policiu requested changes
Please revert additional changes.

2022-10-12 01:14 UTC, valkyrienyanko commented
There is nothing left to review in this PR.

2022-10-12 01:43 UTC, policiu approved these changes
There were two conversations left, but they were pretty minor. Closed them

2022-10-12 02:12 UTC, merged