Enemy use entity system
Valks-Games/sankari pull request #177
Opened 2022-10-14 02:28 UTC by policiu

I did a quick conversion of BasicEnemy to the newer framework. Animations are currently missing.

2022-10-14 06:49 UTC, valkyrienyanko commented on Scripts/Entities/Animations/EntityAnimationDash.cs
> +		if (!((EntityCommandDash)Entity.Commands[EntityCommandType.Dash]).CurrentlyDashing)
Everything on this line confuses me.

2022-10-14 06:50 UTC, valkyrienyanko commented on Scripts/Entities/Commands/EntityCommandDash.cs
> +		DashDurationDone?.Invoke(this, EventArgs.Empty);
Why not use a `GTimer` for consistency?

2022-10-14 06:51 UTC, valkyrienyanko commented on Scripts/Entities/Enemy/BasicEnemy.cs
> +	public override int Gravity { get; set; } = 30000;
I've never seen the `override` or `virtual` keyword be used on props, what does this do?

2022-10-14 06:52 UTC, valkyrienyanko commented on Scripts/Entities/Enemy/BasicEnemy.cs
> +		Delta = (float)delta;
I know that you left this here because `Delta` is only set later in `base._PhysicsProcess(delta)`. I guess there is no good workaround for this.

2022-10-14 06:54 UTC, valkyrienyanko commented on Scripts/Entities/Enemy/BasicEnemy.cs
> +			MoveDir = new Vector2(-1, 0);
Perhaps a enum should be made for readability

```cs
public enum Direction 
{
    West = new Vector2(-1, 0)
} // along with all the other directions and maybe include diagonal directions like NorthEast, NorthWest
```

I don't know the exact syntax for this.

2022-10-14 06:55 UTC, valkyrienyanko commented on Scripts/Entities/Entity.cs
> +		if (Animations.ContainsKey(CurrentAnimation))
Probably not a good idea to have this in a update loop that gets called 60 (or 144 depending on monitor hz). (I'm concerned about performance)

2022-10-14 06:56 UTC, valkyrienyanko commented on Scripts/Entities/Entity.cs
> +	protected TCommand GetCommandClass<TCommand>(EntityCommandType commandType) where TCommand : EntityCommand
This looks like black magic to me 👀

2022-10-14 06:57 UTC, valkyrienyanko commented on Scripts/Entities/Player/Player.cs
> +	public void OnDashDone(object _, EventArgs _2)
mmmm, why not use GTimer for consistency

2022-10-14 06:58 UTC, valkyrienyanko requested changes
Reviewed PR

2022-10-14 06:59 UTC, valkyrienyanko commented on Scripts/Entities/Enemy/BasicEnemy.cs
> +		RayCast2DGroundChecks.Add(RayCastCliffRight);
What was the issue here? Why did you need to do this?

2022-10-14 23:48 UTC, policiu commented on Scripts/Entities/Commands/EntityCommandDash.cs
> +		if (DashReady && !CurrentlyDashing && DashCount != MaxDashes && !Entity.IsOnGround())
What's duplicated. I think it makes sense to have CurrentlyDashing attached to the command that... dashses.

2022-10-14 23:48 UTC, policiu commented on Scripts/Entities/Animations/EntityAnimationDash.cs
> +		if (!((EntityCommandDash)Entity.Commands[EntityCommandType.Dash]).CurrentlyDashing)
AnimationDash relies on CurrentlyDashing which exists in the CommandDash, so we need to grab that.

2022-10-14 23:49 UTC, policiu commented on Scripts/Entities/Enemy/BasicEnemy.cs
> +	public override int Gravity { get; set; } = 30000;
Same as a function. Override replaces the property (for this, we are replacing the default value).

Virtual allows children to override.

2022-10-14 23:50 UTC, policiu commented on Scripts/Entities/Enemy/BasicEnemy.cs
> +		Delta = (float)delta;
Yeah, it's an assignment to the same value, so not that expensive.

2022-10-14 23:54 UTC, policiu commented on Scripts/Entities/Entity.cs
> +	protected TCommand GetCommandClass<TCommand>(EntityCommandType commandType) where TCommand : EntityCommand
It let's me safely cast quickly. It lost most of the safety with the removal of the dictionary check, but still pretty safe.

2022-10-14 23:55 UTC, policiu commented on Scripts/Entities/Enemy/BasicEnemy.cs
> +		RayCast2DGroundChecks.Add(RayCastCliffRight);
IsGround is called by Entity.cs to check if UpdateAir() needs to be called. So without it, UpdateAir is called every frame which messes with Velocity in a way we don't want to a grounded entity..

2022-10-15 00:10 UTC, valkyrienyanko commented on Scripts/Entities/Commands/EntityCommandDash.cs
> +		if (DashReady && !CurrentlyDashing && DashCount != MaxDashes && !Entity.IsOnGround())
Ah nvm I see now

2022-10-15 00:19 UTC, policiu commented on Scripts/Entities/Entity.cs
> +		if (Animations.ContainsKey(CurrentAnimation))
Like I said, BasicEnemy doesn't have any animations (doesn't need any really), so it crashes here. 

The performance gain here negligible.

From my machine:
ContainsKey: 1000 runs ran for 0.0456 ms
Direct access: 1000 runs ran for 0.0189 ms
TryGetValue: 1000 runs ran for 0.025 ms (what I prefer)
GetValueOrDefault: 1000 runs ran for 0.3244 ms

2022-10-15 00:25 UTC, policiu commented on Scripts/Entities/Enemy/BasicEnemy.cs
> +			MoveDir = new Vector2(-1, 0);
Addressed.

2022-10-15 03:29 UTC, valkyrienyanko commented on Scripts/Entities/Entity.cs
> +		if (Animations.ContainsKey(CurrentAnimation))
I understand why this if condition is here now. It just didn't click in my head you know. It's because CurrentAnimation isn't set to anything for Enemy. Perhaps a dummy animation should be created to address this instead of having this ugly if check here? Something like a idle animation for enemy that does nothing.

2022-10-15 03:57 UTC, policiu commented
Done (I couldn't reset you not sure why)

2022-10-15 17:10 UTC, merged